name: langchain_chroma
description: LangChain.dart integration module for Chroma open-source embedding database.
version: 0.1.0+13
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_chroma
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com
publish_to: none

topics:
  - ai
  - nlp
  - llms
  - langchain
  - vector-db

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  chromadb: ^0.1.1
  http: ^1.1.0
  #langchain: ^0.3.3
  langchain:
    git:
      url: https://github.com/KonstantinRr/langchain_dart
      ref: main
      path: packages/langchain
  meta: ^1.9.1
  uuid: ^4.0.0

dev_dependencies:
  test: ^1.24.3
  langchain_openai: ^0.3.3
